version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  web:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: npm run dev
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
